### ISSUE TITLE
feat(multi-selection): add support for multi-lines shifting

### ISSUE THREAD

**Issue by edouard-lopez** [kstenschke/shifter-plugin#14]
Since the addition of [Multiple Selections in PyCharm](http://blog.jetbrains.com/pycharm/2014/09/feature-spotlight-multiple-selections-in-pycharm/) it wourd be nice to be able to select several occurences and increment them in a batch.
Some behaviors must be discussed:
* should we reset the sequence starting at `0`, `1` or at the first item value (e.g. `4`) ;
* do we respect the list values and in/decrement them (e.g. `1, 4, 5, 6` → `2, 5, 6, 7`) or build a new sequence (e.g. `1, 4, 5, 6` → `1, 2, 3, 4`) ?
* etc.

**Comment by ianbytchek** [comment]
:+1:  Yes, please!!!

**Comment by krasa** [comment]
Another case:
```
Comment a1 = new Comment(1,null);
Comment a1 = new Comment(1,null);
Comment a1 = new Comment(1,null);
```
into:
```
Comment a1 = new Comment(1,null);
Comment a2 = new Comment(1,null);
Comment a3 = new Comment(1,null);
```

http://stackoverflow.com/q/30156282/685796

**Comment by kstenschke** [comment]
Thank you Vojtêch for the suggestion and link to stackoverflow. :+1:
Currently shifter sorts multi-line selections alphabetically when shifting them, i think having it detect and enumerate a multi-line selection of identical lines into a sequence might be a cool additional feature.

**Comment by AbcAeffchen** [comment]
:+1: I would love to see the feature suggested by Vojtěch.

**Comment by krasa** [comment]
I needed bunch of unique variable names the other day, and it pissed me off doing it one by one, so I implemented it :)

**Comment by kstenschke** [comment]
wow, sounds cool. looking forward to your pull request :)

**Comment by krasa** [comment]
There won't be any :-) But feel free to copy paste it from my plugin.
