### ISSUE TITLE
Display Github url in plugin description in Intellij

### ISSUE THREAD

**Issue by tomsquest** [kstenschke/shifter-plugin#15]
Beware: heavy change !

In Intellij, using Darcula theme, the link to the project in the Plugin window is hidden in the text.
Could you make it stand out ?

![selection_009](https://cloud.githubusercontent.com/assets/365778/5813998/4d075210-a086-11e4-8933-82922c561fb6.png)

**Comment by kstenschke** [comment]
thanks for the hint, highlightning is added with commit: https://github.com/kstenschke/shifter-plugin/commit/cfa20f9ec45fe7c43040055e2014d2eb691b6964
