### ISSUE TITLE
Make log level shiftable

### ISSUE THREAD

**Issue by tomsquest** [kstenschke/shifter-plugin#16]
I think this addition to the default settings is a good idea :

Given a log file (for example, logback.xml or log4j.xml),
When on a logger tag,
Then the level attribute can be shifted up and down.

Slf4j levels can be a good start (and broader than the levels of JUL or Commons-logging).
Levels : trace, debug, info, warn, error

Example for logback.xml (or logback-test.xml) :

``` xml
<configuration>

  <logger name="com.example" level="debug"/> <!-- debug could be shifted to trace, info warn, error -->

  <root level="warn"><!-- same shifty thingy here -->
    <appender-ref ref="STDOUT" />
  </root>

</configuration>
```

**Comment by kstenschke** [comment]
Hi Thomas, thank you for your input :+1: 
I added the suggested log levels to the default dictionary (https://github.com/kstenschke/shifter-plugin/commit/86c383d7aeecbe58bf5eed678023834d8a72e2c0). They will be available by default with the next release.

**Comment by tomsquest** [comment]
Thanks @kstenschke  !
