### ISSUE TITLE
Ability to generate sequences

### ISSUE THREAD

**Issue by ianbytchek** [kstenschke/shifter-plugin#18]
Hi Kay! Was looking for a plugin that can generate / update sequences but didn't find anything in the plugin repository. Shifter was the closest to the search, looks pretty awesome and mature, so I thought to suggest the idea, though I admit it's a little out of "shifting" context.

It would be great to have the ability to select multiple lines and create a sequence, perhaps this can be the default behaviour of up / down command, i.e., if there is an empty value selected it would instead create the sequence element. This is closely related to #14.

I use this a lot with unit testing (PHPUnit), when the test uses a data provider with large arrays I often index each element so when a test fails on a particular index I know right away what data it was using.

**Comment by kstenschke** [comment]
Hi Ian,
from my own needs of converting lines to lists (sequences) and vice versa, i created the "Shifter" plugin. It by now has a large feature set and might be also what you're looking for: https://plugins.jetbrains.com/plugin/7082 Please let me know if it also fits your needs, or feel free to add feature requests to the shifter plugin.

P.s. If you like shifter and didn't yet- please vote for it on https://plugins.jetbrains.com/plugin/6149 ;)
