### ISSUE TITLE
Shift Down breaks the selected text

### ISSUE THREAD

**Issue by krasa** [kstenschke/shifter-plugin#19]
select: ```Comment a1 = new Comment(1, null);```
Shift Down
result: ```null);, Comment a1 = new Comment(1```

**Comment by kstenschke** [comment]
Shifter (mis)categorizes this selection as a comma-separated list and sorts the items alphabetically.
Please let me know which sort of alteration (and categorization of the selection) you would expect on this selection, maybe it helps me improve shifter.

**Comment by krasa** [comment]
Oh yeah I forgot that it sorts, I expected this result: ```Comment a0 = new Comment(0, null);```
I also forgot that such result can be produced by "my" String Manipulation plugin :-)

Making sorting and incrementing work together for any case in one action is impossible. You would have to introduce an action which would only increment any number occurrences - which might be something that nobody needs :)
