### ISSUE TITLE
It's impossible to shift other aspects

### ISSUE THREAD

**Issue by salarmehr** [kstenschke/shifter-plugin#20]
When for example you want sort some lines alphabetically and there is a least one quotation mark in these lines, it shift between single and double quotes. It seems at the moment, it's impossible to sort them.

**Comment by kstenschke** [comment]
Hi Reza, thank you for your feedback! I will adjust Shifter to fix this issue. Stay tuned

**Comment by kstenschke** [comment]
I tried to reproduce the issue you describe but cannot reproduce it- please try again and re-issue if it the problem persists, with a more detailed example.
