### ISSUE TITLE
Mouse Wheel?

### ISSUE THREAD

**Issue by matiaspub** [kstenschke/shifter-plugin#21]
It's possible to connect functionality on my mouse wheel^ from my keyboard?

**Comment by kstenschke** [comment]
Shifter itself does not provide mousewheel support. But there might be an IDE setting of plugin, or otherwise OS tools (i didn't try but you might have a look into AutoHotKey (windows) or betterTouchTool (Mac)) to connect custom shortcuts to the mousewheel.

**Comment by kstenschke** [comment]
it is possible to use the mouse wheel for invoking shifter - see: https://github.com/kstenschke/shifter-plugin/issues/36
