### ISSUE TITLE
inline-block-block-block-block...

### ISSUE THREAD

**Issue by matiaspub** [kstenschke/shifter-plugin#22]
if i Shift CSS display value, when set to inline-block, next value is inline-block-block, e.t.c with -block additions.
I think it's right, to find whole(maximum greater) predefined value, before change.

**Comment by kstenschke** [comment]
While editing CSS (or SCSS) files this issue should be fixed with commit https://github.com/kstenschke/shifter-plugin/commit/77fe8ba40ffb9a5369a98f4e505f74a9f42770d9, note: for HTML or other files hyphenated words will still be treated as two separate words.
