### ISSUE TITLE
Unable to configure settings in IntelliJ 2016.1

### ISSUE THREAD

**Issue by duponter** [kstenschke/shifter-plugin#24]
Recently I migrated from IntelliJ 15.0.4 to IntelliJ 2016.1. (Ultimate edition)
While the Shifter plugin still works in the latest IntelliJ, I am not able to configure it anymore. 
In IJ 15, I could change them via Preferences > Other Settings > Shifter.
In IJ 2016.1, Shifter disappeared from the Other Settings list.

Thanks for looking into it,
Regards,
Erwin

**Comment by kstenschke** [comment]
Thank you Erwin for your feedback. I will have a look into this.

**Comment by krasa** [comment]
https://youtrack.jetbrains.com/issue/IDEA-150516
you need to split ProjectComponent and Configurable  into separate classes and use

    <extensions defaultExtensionNs="com.intellij">
        <projectConfigurable ... />
    </extensions>

**Comment by kstenschke** [comment]
Hi Erwin, from Shifter version (just released), Shifter settings should work also in Idea version 2016.1 and onwards.

**Comment by duponter** [comment]
Version 1.3.0 installed and it works like a charm.
Thanks for your effort.
