### ISSUE TITLE
CRITICAL: Duplicates removal also removes non-duplicated values

### ISSUE THREAD

**Issue by senaria** [kstenschke/shifter-plugin#26]
Shifting up and accepting the removal of duplicated entries will "remove / not provide" the first element of the shifted result.

Example:

```
1
2
3
1
2
3
```

Selecting these 6 lines and shifting it up will result in:

```
2
3
```

If I select an empty line above and below it seems to work, but this is dangerous.

**Comment by kstenschke** [comment]
Thank you Senaria for reporting this issue.
It is corrected with ae5eff21835450c1b953dc7fc6436dbfa8741720 👍
