### ISSUE TITLE
Shortcuts on Mac

### ISSUE THREAD

**Issue by texmedia** [kstenschke/shifter-plugin#27]
I am having issues to use this plugin as it does not shift anything
on a MAC Jetbrains IDE when using SHIFT-ALT-COMMAND + Comma etc.
I do also not find the command in the keymap settings of PHPStorm to set
the shortcuts manually.

Can you help? Thanks!

**Comment by kstenschke** [comment]
Hi texmedia, 
i am using Shifter on Mac OS myself, it does work- maybe the problem has to do with your country's keyboard layout? However you can change Shifter's key combo's in the "Keymap" section of your IDE's settings.

**Comment by ubaierbhat** [comment]
<kbd>Cmd</kbd>+ <kbd>Shift </kbd>+ <kbd>Alt </kbd>+ <kbd>K</kbd> conflicts with intellij default for "Convert Java File to Kotlin"
