### ISSUE TITLE
enhancement request: more CSS units

### ISSUE THREAD

**Issue by FireCoding** [kstenschke/shifter-plugin#28]
I use this plugin all the time for max dev speed -- thank you for all your efforts!

It would be WONDERFUL if CSS value shifting supported more units, e.g.:
- rem
- vw
- vh
- vmin
- vmax

**Comment by kstenschke** [comment]
In the "dictionary" section of Shifter's plugin settings you can configure your own shifting dictionary for a specific file type (e.g. css, html) or general vocabulary.

**Comment by FireCoding** [comment]
Sorry I wasn't clear.  I meant to emphasize _**value**_ shifting.  The dictionary is for defining sets of terms as I understand it.

For example, if I see `10px` I can shift up to `11px` because `px` is supported.  However if I see `10rem` I _**cannot**_ shift up to see `11rem`.

I took a quick look inside...  looks like all I have to modify is `/src/com/kstenschke/shifter/models/shiftertypes/CssUnit.java` ??  I will try to send a PR soon.

**Comment by Tech-Nomad** [comment]
Hey, thanx for the great plugin! 
Is it possible to add support for seconds as well? Like for transitions:
`transition: all .3s ease;
`
right now i have to mark only the number to get it shifted, otherwise the "all" value gets shifted
