### ISSUE TITLE
Changing the value with the mouse wheel

### ISSUE THREAD

**Issue by GriNAME** [kstenschke/shifter-plugin#36]
Please add the option to change the value of the selected numbers by scrolling the mouse wheel. That is, you must select a number, hover over the selected number, and spin the mouse wheel. Same as dev tools Google Chrome. It can be added only with a clamped hotkey if this makes development easier.

**Comment by kstenschke** [comment]
Hi Gregory, thank you for your input.
It should be possible to use the mouse wheel already: by setting up a system tool (e.g. Karabiner on Mac, Autohotkey (i think) on windows) to map wheel movement, application-specific to simulate pressing the desired keyboard shortcut(s).

Before implementing custom mouse wheel support to a plugin, i'd prefer the IDE allowing for mouse wheel interactions via its regular Keymap settings, which it unfortunately does not yet. You can vote for a feature like that in the IDE e.g. here:
https://youtrack.jetbrains.com/issue/IDEA-112296
https://youtrack.jetbrains.com/issue/IDEA-108023

**Comment by GriNAME** [comment]
@kstenschke It perfect! Thank you a lot!
