### ISSUE TITLE
Underscore separated names

### ISSUE THREAD

**Issue by lkb2k** [kstenschke/shifter-plugin#37]
Great plugin.  Wanted to add a feature request to be able to shift between camelCase and underscore separated names instead of minus separated.  My project has a lot of camel case fields mapped to underscore separated sql columns, so being able to copy/paste and shift those would be awesome.

**Comment by krasa** [comment]
Check out https://plugins.jetbrains.com/plugin/2162-string-manipulation

**Comment by kstenschke** [comment]
Hi lkb2k, thanks for the suggestion! This should come with the next release.

**Comment by kstenschke** [comment]
Since the latest release (1.7.7) of Shifter, selected underscore separated names can be shifted into camel case and vice versa.
