### ISSUE TITLE
Multi-line sorting results in single line

### ISSUE THREAD

**Issue by speedbomb** [kstenschke/shifter-plugin#39]
If I shift a multi-line selection to sort it alphabetically, Shifter will sort it correctly, but removes all line breaks:
```
ul.ring > li {
    background-position: 3px 4px;
    background-image: url(images/bullet_ring.png);
}
```
with only the two lines with CSS properties selected will result in:
```
ul.ring > li {
    background-image: url(images/bullet_ring.png); background-position: 3px 4px;
}
```
Sorting associative arrays e.g. in PHP keeps the line breaks, so I think, some weird setting is responsible for the unwanted result. Just can't find any line break settings in code style for CSS or SCSS files.

**Comment by speedbomb** [comment]
Tested again with Shifter 1.7.7 and PhpStorm 2017.3.5 → solved

**Comment by kstenschke** [comment]
:-) thanks for your updated feedback.
