### ISSUE TITLE
Automatic popup or auto-suggestion?

### ISSUE THREAD

**Issue by flexjoly** [kstenschke/shifter-plugin#51]
Hi,

Thanks for this wonderful plugin!! JetBrains should buy this from you and integrate it as default 😉 !!

I hope this is not a dummy question (I am quite new to phpStorm), but would it be possible that this plugin integrates with code-completion or auto-suggestions so that the little lightbulb-icon is shown when shifter can do something with the current line/selection? Or with the inspections?

Greetz, flexJoly

**Comment by kstenschke** [comment]
Hi flexJoly,
thank you for the flattering compliment ;-)
I am afraid the variaty of shifting-types is too vast, leading to too many lightbulb-icons if this was implemented. Inspections indicate (fixable or not) code-smells, whereas the modification options added by Shifter do not in particular fix issues, but try to help you do the pobably possibly intended changes for a given context.
A mechanism maybe somehow simlar to what you describe, is implemented by Shifter when a context allows for multiple modification types - it than opens a popup menu to select the intended modification.

Greetings, Kay
